### ISSUE TITLE
Default vulnerabilities are not working 

### ISSUE THREAD

**Issue by Sergicles** [rapid7/hackazon#1]
Hi All

Just wondering about the current master... 

It seems like the default vulnerabilities are hit and miss. As an authenticated user, for instance, one command injection works. SQL Injections don't seem to work (some, not all), although HTTP error is returned. It's not set to blind, so I am not sure if this is the expected bahaviour or something is not working well in there. 

For example, adding SQL injection to any search page fields doesn't seem to work on my installation. 

Any advise would be great. Thanks!

**Comment by fredfalcon** [comment]
There is a bounty on this issue: http://www.coderbounty.com/issue/42/

**Comment by Erazem** [comment]
Hi Sergicles, I am encountering the same problem.  Can you share the syntax of any SQL injection(s) that _are_ working?

**Comment by fredfalcon** [comment]
Here is a list of vulnerabilities - maybe it would help to test them all and mark which ones are working or not.  https://github.com/rapid7/hackazon/blob/master/VULNERABILITIES.md

**Comment by sambowne** [comment]
I found a solution for the blind SQLi. (See #11)

In ./classes/PDOV/Connection.php, at the end of the startBlindness function,
after line 207, add this line:

```
    $this->pixie->debug->display_errors = true;     // FIX SQLi
```

The resulting startBlindness function looks like this:

---

```
public function startBlindness($vulnFields)
{
    if (!$vulnFields || $this->vulnerable) {
        return;
    }

    if (!is_array($vulnFields) && !($vulnFields instanceof \ArrayObject)) {
        $vulnFields = [$vulnFields];
    }

    $this->vulnerable = false;

    foreach ($vulnFields as $field) {
        if (!($field instanceof VulnerableField)) {
            continue;
        }

        if ($field->isVulnerableTo('SQL')) {
            $this->vulnerable = true;
            if ($field->getVulnerability('SQL')->isBlind()) {
                $this->dispErrorStates[] = $this->pixie->debug->display_errors;
                $this->pixie->debug->display_errors = false;
                $this->isBlinded = true;
                return;
            }
        }
    }

    $this->isBlinded = false;
    $this->pixie->debug->display_errors = true;   // FIX SQLi
}
```

---

**Comment by DenisPodgurskiy** [comment]
Hi guys

I know that this is too late for the answer, but you can just modify config file in /assets/config/parameters.php and set 
display_errors => true.

After that you should see SQL errors, so SQL injections will work as required.
