### ISSUE TITLE
Admin page error after login

### ISSUE THREAD

**Issue by ghost** [rapid7/hackazon#14]
I use Ubuntu 16.04.2 LTS minimal server to install hackazone. After login i found some error like this in admin page

Fatal error: Uncaught Error: Call to a member function getClassAnnotation() on null in /var/www/hackazon/modules/vulninjection/classes/VulnModule/AnnotationReader.php:51 Stack trace: #0 /var/www/hackazon/modules/vulninjection/classes/VulnModule/Config/ContextMetadataFactory.php(88): VulnModule\AnnotationReader->getClassAnnotation('App\\Controller\\...', 'VulnModule\\Conf...') #1 /var/www/hackazon/modules/vulninjection/classes/VulnModule/Config/Context.php(741): VulnModule\Config\ContextMetadataFactory->getMetadata('account', 'orders', 'web') #2 /var/www/hackazon/modules/vulninjection/classes/VulnModule/VulnerabilityMatrixRenderer.php(106): VulnModule\Config\Context->getURL() #3 /var/www/hackazon/modules/vulninjection/classes/VulnModule/VulnerabilityMatrixRenderer.php(85): VulnModule\VulnerabilityMatrixRenderer->calculateVulnMatrix(Object(VulnModule\Config\Context), 3) #4 /var/www/hackazon/modules/vulninjection/classes/VulnModule/VulnerabilityMatrixRenderer.php(85): VulnModule\VulnerabilityMatrixRenderer->calculateVulnMatr in /var/www/hackazon/modules/vulninjection/classes/VulnModule/AnnotationReader.php on line 51

Some body help me??

**Comment by kinhelm** [comment]
For dirty fix 👎  : remove try catch 
there : /var/www/hackazon/modules/vulninjection/classes/VulnModule/AnnotationReader.php on line 51
(and 77)
to set `$result` to `null`

**Comment by DenisPodgurskiy** [comment]
At the moment I see that everything works with php 5.6, but we do have some issues with php7.
Which php version do you have?

**Comment by dentonk** [comment]
To work with php7 I had to change the 
`} catch (\Exception $e) {` 
to
`} catch (\Throwable $t) {`
(note, there are a few of those in the AnnotationReader.php file and I changed them all)

See: http://php.net/manual/en/language.errors.php7.php
There may be unexpected consequences for making this change but it seems to have worked for me.
