### ISSUE TITLE
503 Service Temporarily Unavailable - following installation

### ISSUE THREAD

**Issue by yovzed** [rapid7/hackazon#16]
Followed the precise installation notes + manual
Logged in to hackazon.lc and followed the steps
When I click INSTALL

I get 503 Service Temporarily Unavailable - following installation

DB is created but remained empty

**Comment by ghost** [comment]
same problem here

**Comment by DenisPodgurskiy** [comment]
Hi guys

1) Did you have rewrite mode enabled on your apache server?
2) What is the error message in the apache log?
3) Can you modify /assets/config/parameters.php and set 'display_errors'=>true and check the installation once again? 


Below you can find some pre-existing virtual machine that you can use:
You can find OVA file (VMWare image) with installed Hackazon web application by the url https://drive.google.com/open?id=0B7KzT3FP4YOoRkp6empQQi1WTXM

OS: hackazon/hackazon

MySQL: hackazon/hackazon

Web app: admin/hackazon

**Comment by ghost** [comment]
The error of PHP was that `date.timezone` wasn't set.
I also gave permissions to the project directory.

It's working now.


Thanks!

**Comment by iNoSec** [comment]
> The error of PHP was that `date.timezone` wasn't set.
> I also gave permissions to the project directory.
> 
> It's working now.
> 
> Thanks!

Can you say me how to do it?? because they dont really care at rapid7 lol
