### ISSUE TITLE
.ova file does not have a network interface

### ISSUE THREAD

**Issue by TobinShields** [rapid7/hackazon#21]
I went to download the .ova file linked on the Wiki, but when I went to grab the IP using ifconfig it looks like the network interface is disabled (just loppback displays). I thought that it was something on my end using VirtualBox, but I was able to download and bridge other VMs without an issue. I was even able to manually install Hackazon onto Ubuntu 14 and get it running in VirtualBox, so it makes me think that something is wrong with the .ova file.

**Here is an error that I got on startup:**
![Error Screenshot](https://i.stack.imgur.com/x8wVx.png)

**And here is the output when I run ifconfig**
![ifconfig output screenshot](https://i.stack.imgur.com/MePSh.png)

Is this just an issue on my part or is anyone else able to confirm this?

**Comment by JavanXD** [comment]
@DenisPodgurskiy could you please help us and explain how to use the .ova file?

**Comment by boris-sathya** [comment]
Problem is "Predictable Network Interface naming" renames your standard eth0 to something like enpxxxx

Find out the interface
`dmesg | grep -i eth
`

edit /etc/network/interfaces to something like

```
auto enpxxxx
iface enpxxxx inet dhcp
```

Reboot

**Comment by TobinShields** [comment]
That did it! Thanks tons. Is that a misconfiguration in the OVA?
